import type { Metadata } from "next";
import { productSans } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${productSans.variable} antialiased bg-gradient-to-br from-orange-50 to-pink-50`}
      >
        {children}
      </body>
    </html>
  );
}
