import type { Metadata } from "next";
import { productSans } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "BKP 5.0",
  description: "Generated by create next app",
  icons: {
    icon: "/gdgico.svg",
    apple: "/gdgico.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${productSans.variable} antialiased  bg-gradient-to-br from-orange-50 to-pink-50 font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
